### ISSUE TITLE
Hello, Thanks for the bot

### ISSUE THREAD

**Issue by amr21006** [RomanGorbatko/futures-bot#1]
I don't know why that message appear every time I run the bot
![Capture](https://github.com/RomanGorbatko/futures-bot/assets/1961255/03297518-9a56-47fd-961d-437217b1198b)

can you tell me the solution?

**Comment by amr21006** [comment]
thank you for your response 
is this what you need?
![Capture](https://github.com/RomanGorbatko/futures-bot/assets/1961255/c1d3f18c-c62c-4769-b1c4-d2e93a6349d5)

**Comment by RomanGorbatko** [comment]
I mean, insert `print(event)` at 97 line:
```python
def handle_socket_message(event):
    print(event)
    s = event["ps"]
```

And show me console output.

**Comment by RomanGorbatko** [comment]
Strange behavior because i see `ps` key on your screen at every message:
<img width="620" alt="image" src="https://github.com/RomanGorbatko/futures-bot/assets/975959/ac4e4ca5-9a08-434b-9399-c753ee4f4d6f">

**Comment by amr21006** [comment]
maybe one the coins drops when getting the data?

**Comment by amr21006** [comment]
Thank you
